---

env:
  # Allow outbound network conenction (Coveralls requires this to post results).
  - USENETWORK=true

  # Puppet validator strictness.
  - STRICT_VARIABLES=true
  - STRICT=error

# We don't require sudo so we can be tested in the (faster) container based environment.
sudo: false

# Use trusty rather than precise.
dist: trusty

# Provide entropy to speed up the jruby installations.
addons:
  apt:
    packages:
      - haveged

language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.1
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.2
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.3
    env: PUPPET_VERSION="~> 4.0" FORGE_DEPLOY="true" GITHUB_RELEASE="true"
  - rvm: jruby-head
    env: PUPPET_VERSION="~> 4.0"
    jdk:
      - openjdk7
      - oraclejdk7
      - oraclejdk8
      - openjdk6
  - rvm: jruby-18mode
    env: PUPPET_VERSION="~> 4.0"
    jdk:
      - openjdk7
      - oraclejdk7
      - oraclejdk8
      - openjdk6
  - rvm: jruby-19mode
    env: PUPPET_VERSION="~> 4.0"
    jdk:
      - openjdk7
      - oraclejdk7
      - oraclejdk8
      - openjdk6

# Call the default puppetlabs test provider which will validate, lint, and test.
script:
  - 'bundle exec rake test'

deploy:
  - provider: puppetforge
    user: "aolabs"
    password:
    secure: p3v+RqS1QpWkzx0CwSZOcDcn99+mjw4U5OynqQY0v/PIoie6E8eLS+vNZpMmOxxi6cjkBHS+69C8TzZN6HjFOi2i+Nwl6i8fiXxYgf0Q86OFcY6xnqZGnNLNKBGvZJH7K3uhIcBi6QFy+DA/WZHQsazkfsmcUoiFOP8FXl4wnWyG7Vo9dq7w+ZAHSggYfZ7UAtjfxXlzNvYEj8GfrnAvhJ/uoyRifGPxBXwjslUCDJ67NIDYkx0qz56szJrDEjUYEPMiPB0IzfNeJCoFob1boruGclY1Md3oGG76dOttajKEw5qUv0ytYrS1mVwGX2dxQEXWQP5YC4zD4D8kEzMYZ48yjphYPUS/qUNLe5z/B5lROXz5Zln7fIFo5JRYrq9FmtsoQu+C6SMVpC/XhpUlg0edU3TcqwscyAGaD5EZYbUzblsbDaDMkAx03dn/KcDnL3maB/38ppUnuW36Johd6mfUZSr9DVK/g2EPzTbUbmeF9rjL0vCvdZ51mElfSX2YzD1IPtB0eI50X3UzE9ByE/0PPcCnD6T5nGPqA2gcexeS47n50M1kedmK38LOD/y4CDJqwaedV7OFNizr4P/xXmYUaVhse6oi7RvBlgLsFmbCmMQ35zKU8U2uIDtuO6J6iBstXU/8eLiK4rujRU5VqROuhSmun/0iEO2ClTti9AQ=
    on:
      tags: true
      all_branches: true
      condition: "$FORGE_DEPLOY=true"
  - provider: releases
    api_key:
      secure: YOUR_API_KEY_ENCRYPTED
    #file: "FILE 1"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: "$GITHUB_RELEASE=true"
